# System Settings
kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G


# Global Project Settings - set name in settings.gradle.kts
version=2.1.18
group=de.miraculixx
projectName=BMMarker
description=Add a marker command to easily setup your markers & marker sets ingame without touching any configs
author=Miraculixx
licence=MIT
modrinthProjectId=bmarker


# Minecraft Settings
gameVersion=26.2
publishState=release


# Fabric Settings
modid=bmarker
# server, client, *
environment=*
fabricSupportedVersions=>=26.2
fabricDependencyVersions=>=26.2
adventureVersion=7.1.0
silkVersion=1.12.0
usePermissions=true
useConfig=false


# Paper Settings
paperSupportedVersions=>=1.20.5
foliaSupport=false
useBrigadier=true
