package de.miraculixx.bm_marker.utils.enums

enum class MarkerType(val args: List<MarkerArg>) {
    POI(
        listOf(
            MarkerArg.ID,
            MarkerArg.LABEL,
            MarkerArg.WORLD,
            MarkerArg.POSITION,
            MarkerArg.ICON,
            MarkerArg.MIN_DISTANCE,
            MarkerArg.MAX_DISTANCE
        )
    ),
    HTML(listOf()), // Unusable
    LINE(
        listOf(
            MarkerArg.ID,
            MarkerArg.LABEL,
            MarkerArg.WORLD,
            MarkerArg.ADD_POSITION,
            MarkerArg.DETAIL,
            MarkerArg.LINK,
            MarkerArg.NEW_TAB,
            MarkerArg.DEPTH_TEST,
            MarkerArg.LINE_WIDTH,
            MarkerArg.LINE_COLOR,
            MarkerArg.MIN_DISTANCE,
            MarkerArg.MAX_DISTANCE
        )
    ),
    SHAPE(
        listOf(
            MarkerArg.ID,
            MarkerArg.LABEL,
            MarkerArg.WORLD,
            MarkerArg.ADD_EDGE,
            MarkerArg.HEIGHT,
            MarkerArg.DETAIL,
            MarkerArg.LINK,
            MarkerArg.NEW_TAB,
            MarkerArg.DEPTH_TEST,
            MarkerArg.LINE_WIDTH,
            MarkerArg.LINE_COLOR,
            MarkerArg.FILL_COLOR,
            MarkerArg.MIN_DISTANCE,
            MarkerArg.MAX_DISTANCE
        )
    ),
    EXTRUDE(
        listOf(
            MarkerArg.ID,
            MarkerArg.WORLD,
            MarkerArg.LABEL,
            MarkerArg.ADD_EDGE,
            MarkerArg.HEIGHT,
            MarkerArg.MAX_HEIGHT,
            MarkerArg.DETAIL,
            MarkerArg.LINK,
            MarkerArg.NEW_TAB,
            MarkerArg.DEPTH_TEST,
            MarkerArg.LINE_WIDTH,
            MarkerArg.LINE_COLOR,
            MarkerArg.FILL_COLOR,
            MarkerArg.MIN_DISTANCE,
            MarkerArg.MAX_DISTANCE
        )
    )
}